// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_aboutstatus_aboutheading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_aboutstatus_aboutheading));
        
        string IMigrationMetadata.Id
        {
            get { return "202106092054581_add_aboutstatus_aboutheading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
